name: Regression Tests

on:
  push:
    branches: [ "master" ]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install -r requirements.txt;
    - name: Robot Framework
    - uses: joonvena/robotframework-docker-action@v1.0
      with:
        # Shared memory that Docker container is allowed to use
        allowed_shared_memory: '1g'
        #    Browser to use
        browser: 'chrome'
        # Execute tests in parallel
        robot_threads: '1'
        # Extra settings for parallel execution. https://github.com/mkorpela/pabot#command-line-options
        pabot_options: ''
        # Extra options for robot command
        robot_options: '' 
        # Color depth of the virtual screen
        screen_color_depth: 24
        # Height of the virtual screen
        screen_height: 1080
        # Width of the virtual screen
        screen_width: 1920
        # Directory where Robot tests are located in the repository
        robot_tests_dir: 'Tests'
        # Where will the report from test be saved
        robot_reports_dir: 'Tests'
